microsoft/BitBLAS

- python/bitblas/cache/operator.py
- python/bitblas/ops/operator.py
- python/bitblas/wrapper/general.py
As some frameworks might require enabling cuda graph for better performance, this pull request adds the cuda stream interface to the cuda wrap function in order to support cuda graph.
> [CUDA GRAPH] Support Cuda Stream in the Wrap Function

- requirements.txt
Currently the bitblas package will not run installed from a wheel because torch is not required by the package, when it clearly is needed.
Example reproduction of bug:
```bash
> wget https://github.com/microsoft/BitBLAS/releases/download/v0.0.1/bitblas-0.0.1dev0+ubuntu.20.4.cu120-py3-none-any.whl
> pip install bitblas-0.0.1dev0+ubuntu.20.4.cu120-py3-none-any.whl
> python benchmark/operators/benchmark_bitblas_matmul.py
Traceback (most recent call last):
File "/home/michael/code/BitBLAS/benchmark/operators/benchmark_bitblas_matmul.py", line 4, in <module>
from bitblas.utils.target_detector import auto_detect_nvidia_target
File "/home/michael/venvs/bitblas/lib/python3.10/site-packages/bitblas/__init__.py", line 19, in <module>
from . import gpu  # noqa: F401
File …
```
> Add `torch` as a requirement

- python/bitblas/gpu/intrin/lop3.py
- requirements-dev.txt
- requirements.txt
- testing/cpp/lop3_type_conversion/fast_decoding.hpp
- testing/cpp/lop3_type_conversion/lowprecision_to_float16.cu
fixed the issue : https://github.com/microsoft/BitBLAS/issues/24#issue-2263511731
> [Kernel] Extend Fast Decoding to UINT2 + QZeros

- integration/BitNet/eval_correctness.py
- integration/BitNet/eval_ppl.py
- integration/BitNet/eval_utils.py
- integration/BitNet/requirements.txt
- python/bitblas/base/roller/policy/tensorcore.py
- python/bitblas/base/utils.py
- python/bitblas/cache/operator.py
- python/bitblas/ops/general_matmul.py
- python/bitblas/utils/target_detector.py
1. add the requirement.txt for bitnet integration
2. disable accelerate as it might enable cuda graph.
> [BitNet] Disable accelerate for BitNET

- python/bitblas/quantization/quantization.py
- testing/python/operators/test_general_matmul_fp8.py
This pull request primarily focuses on refining the type conversions and adjusting the precision in the testing function. The changes are aimed at improving the efficiency and accuracy of the code.
Here are the key changes:
Type conversion refinement:
* [`python/bitblas/quantization/quantization.py`](diffhunk://#diff-503bb115fee1e2a4e550c48b1e81d65e691d4c53bc73ed562cb781cce8a9022dL145-R147): In the function `_tir_u8_to_f8_e4m3_to_f16`, the type of the shift operation has been changed from `int16` to `uint16`. Also, the calculation of `s_f16` and `e_f16` has been modified to use bitwise operations.
Precision adjustment:
* [`testing/python/operators/test_general_matmul_fp8.py`](diffhunk://#diff-9f97faae9b43c6d8e853d0b80a7649c8b917ec59cf041943de490bf8a22e1ea6L169-R169): In the function …
> [DEV][FP8] Improve e4m3 decoding

- python/bitblas/base/roller/hint.py
- python/bitblas/base/roller/policy/tensorcore.py
- python/bitblas/gpu/intrin/lop3.py
- python/bitblas/ops/general_matmul.py
- python/bitblas/ops/impl/matmul_dequantize_impl.py
- python/bitblas/quantization/quantization.py
- testing/python/operators/test_general_matmul_fp8.py
This pull request includes changes to several Python files in the `bitblas` library, with the primary goal of improving support for different data types and making the code more robust. This includes changes to the `hint.py`, `tensorcore.py`, `lop3.py`, `general_matmul.py`, and `matmul_dequantize_impl.py` files. The changes can be grouped into three main categories: updates to the `hint.py` and `tensorcore.py` files to handle different data types, improvements to the `lop3.py` file to better handle different bit sizes, and changes to the `general_matmul.py` and `matmul_dequantize_impl.py` files to add assertions and handle different bit sizes.
Handling different data types:
* [`python/bitblas/base/roller/hint.py`](diffhunk://#diff-2484769c3525207d4e2b7031c12b42e99b8f16eab8f442e12c87d67930b …
> [BUGFix] Fix UINT/INT8 dequantize implementation and optimize the schedule template for float32 accum

- python/bitblas/base/roller/__init__.py
- python/bitblas/base/roller/hint.py
- python/bitblas/base/roller/policy/tensorcore.py
- python/bitblas/gpu/intrin/lop3.py
- python/bitblas/gpu/matmul_analysis.py
- python/bitblas/module/__init__.py
- python/bitblas/ops/general_matmul.py
- python/bitblas/ops/general_matmul_splitk.py
- python/bitblas/ops/impl/batch_matmul_dequantize_impl.py
- python/bitblas/ops/impl/batch_matmul_impl.py
- python/bitblas/ops/impl/matmul_dequantize_impl.py
- python/bitblas/ops/impl/matmul_dequantize_splitk_impl.py
- python/bitblas/ops/impl/matmul_splitk_impl.py
- python/bitblas/ops/operator.py
- python/bitblas/quantization/quantization.py
- testing/python/operators/test_general_matmul_fp8.py
- testing/python/operators/test_general_matmul_splitk_ops.py
This pull request introduces a number of changes across the `python/bitblas` package in order to improve the functionality of the BitBlas library. The changes include updates to the `Rasterization` and `TensorCoreExtraConfig` classes, modifications to the `fast_decode_impl` method, and the addition of the `MatmulWithSplitK` class.
Updates to `Rasterization` and `TensorCoreExtraConfig` classes:
* [`python/bitblas/base/roller/__init__.py`](diffhunk://#diff-978183b8170138304d9129386764cdab461eb69016439b00a227e433f5abb860R4): Imported new `Rasterization` classes.
* [`python/bitblas/base/roller/hint.py`](diffhunk://#diff-2484769c3525207d4e2b7031c12b42e99b8f16eab8f442e12c87d67930bbb1f2R214-R219): Added a new method `tensorcore_legalization` to the `TensorCoreExtraConfig` class.
Modifications to …
> [Feature] Enhancing MatmulOps with Splitk Support

- .gitignore
- python/bitblas/module/__init__.py
- testing/python/operators/test_matmul_dequantize_ops.py
Issue#24: FIx a bug of repack AutoGPTQ quantized parameters
modified: python/bitblas/module/__init__.py
add "zero_mode=quantized" & asymmetric zeros of "source_format=uint" testing
> [Dev] Issue#24: FIx a bug of repack AutoGPTQ quantized parameters

- python/bitblas/utils/target_detector.py
There are two bug fixes in this PR
1. In a multipe gpu setup,  https://github.com/ModelCloud/GPTQModel/pull/39 may need to execute on a single gpu in a multi-gpu env where the gpu_id is not 0 according to nvidia-smi. The current setup assume TVM target is always the first gpu (index=0) which is incorrect.  Fix = pass in `gpu_id: int` and make `nvidia-smi --id` use it
2. Nvidia makes several oem, non-public, version of A100 such as PG506-230 which is part of the official and opensource driver supported device list. They are essentially A100 with different VRAM sizes.  Remap this model so TVM can be matched to A100 correctly.  There may be other gpus affected so added TODO to move this into a helper re-mapper method. Fix = manual remap. 
TEST
@LeiWang1999
> [FIX] GPU detection in  multigpu env and OEM A100 not matching TVM

- python/bitblas/utils/target_detector.py
nvidia-smi uses PCI_BUS_ID order but python program may be launched using default which is not PCI_BUS_ID order for gpu. If the env values do not match, wrong gpu is returned for `gpu_id`. Validate the env and raise error if issue exists. 
TESTS
> [FIX] Must validate ENV settings or wrong gpu selected  by  nvidia-smi  

- python/bitblas/utils/target_detector.py
A model was missing in the previously merged nvidia oem a100 remap. Refractored so the code is not static but a dictionary lookup for better future additions. Ideally, this code should be part of tvm and not downstream consumer of tvm like bitlbas.
> Fix gpu model missing from tvm target remap

- README.md
This pull request includes a modification to the support matrix in the `README.md` file. The changes mainly involve updating the `Accum_dtype` and `Out_dtype` fields for several data types. 
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L58-R67): Updated the support matrix to reflect changes in the accumulation and output data types for FP16, FP4_E2M1, FP8_E4M3, INT8, UINT4/INT4, UINT2/INT2, UINT1, and NF4. The `Accum_dtype` for these data types has been changed to FP32/FP16, and the `Out_dtype` has been set to FP16.
> [Readme] Update support matrix in README

- .github/workflows/ci.yml
- bitblas/ops/impl/__init__.py
- bitblas/ops/impl/base.py
- bitblas/ops/impl/batch_matmul_impl.py
This pull request introduces a number of changes primarily aimed at refactoring the `bitblas/ops/impl/batch_matmul_impl.py` file for better code organization and maintainability. The changes also include modifications to the Continuous Integration (CI) workflow and some minor adjustments in other files.
Refactoring of `bitblas/ops/impl/batch_matmul_impl.py`:
* The functions `matmul_nt` and `matmul` have been replaced with two new classes: `BatchMatMulEmitter` and `BatchMatMulSelector`. These classes encapsulate the same functionality but provide a more structured and maintainable approach.
* The `BatchMatMulEmitter` class is responsible for emitting the TIR script for batch matrix multiplication. It includes methods for validating dimensions, applying bias, and converting data types.
* …
> [CI] Edit the notify setting in our CI

- bitblas/cache/operator.py
Before this change, the default for `database_path` would evaluate to the value that `BITBLAS_DATABASE_PATH` had upon the definition of the function, ignoring changes made using `set_database_path`.
> Fix database path default

- install.sh
- setup.py
Update:
setup.py
install.sh
set(USE_CUDA ON) --> set(USE_CUDA /usr/local/cuda)
> [Issue 62] flexible whl for different cuda version

- setup.py
When running 'pip install -e .', the number of parallel make jobs can cause memory exhaustion.
This patch limits the maximum parallel jobs to the maximum thread number.
> Limiting parallel jobs for local build

- artifact/QuickStart/0.torch_inference_and_onnx_export.py
For operator 'aten::scaled_dot_product_attention'.
Error message:
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 13 is not supported. Support for this operator was added in version 14, try exporting with this version.
> Change ONNX opset number to 14

- bitblas/gpu/matmul_mma_dequantize.py
- bitblas/module/__init__.py
- bitblas/ops/general_matmul/__init__.py
This pull request includes several changes to improve device compatibility and streamline the weight transformation process in the `bitblas` module. The most important changes involve modifying various functions to ensure they correctly handle the device context for GPU operations.
* [`bitblas/module/__init__.py`](diffhunk://#diff-31b9ec55b0bfed86accdccaf81747ebf9e26d1c36281acfede97662678812407L315-R320): Updated the `repack_from_gptq` method to accept a `device` parameter, allowing the weight transformation to be performed on the specified device.
* [`bitblas/ops/general_matmul/__init__.py`](diffhunk://#diff-74fe5dd2824cb03a0fb2b0a913a2fc5caeb9c08e5368c318cd32b3af7e6f52edL606-R606): Modified the `transform_weight` method to use the device of the input weight tensor instead of defaulting …
> [BUG] Set Device when kernel be applied into Multiple GPUs.

- bitblas/gpu/matmul_mma_dequantize.py
- bitblas/module/__init__.py
- bitblas/ops/general_matmul/__init__.py
Following the changes in PR #133, which set the default memory scope from `shared` to `shared.dyn`, the FP8 Tensorcore has not been fully tested. As a result, we missed the registeration for FP8 `ldmatrix` operations on dynamic shared memory, leading to issue #160
> [BUGFix] Resgiter missing FP8 LDMATRIX Instructions for dynamic shared memory

- bitblas/gpu/matmul_mma_dequantize.py
- bitblas/module/__init__.py
- bitblas/ops/general_matmul/__init__.py
> [BugFix] Fix BitBLAS Linear with BFloat16 input

- install_amd.sh
- python/ladder/arch/MI250.py
- python/ladder/header.py
- python/ladder/policy/default.py
- python/ladder/policy/tc.py
- python/ladder/relay/integration.py
- python/ladder/relay/transform/ladder_gemm_perfectmatmul.py
- python/ladder/relay/transform/welder_tune_pass.py
- python/ladder/schedule/ladder_intrin.py
- python/ladder/schedule/tir_base.py
- python/ladder/schedule/tir_ladder.py
- python/ladder/tvm_build.py
- python/ladder/utils.py
This pull request includes various changes to the `ladder` project, primarily focusing on adding support for ROCm (AMD GPUs), enhancing the handling of different architectures, and improving the performance and functionality of the codebase.
* [`python/ladder/arch/MI250.py`](diffhunk://#diff-d94affec1634dbb078e4e9629b4b7808a45465d8b5725b037e1358e6f50ce028L18-R18): Updated the `target` initialization to include `--mcpu=gfx90a` for ROCm.
* [`python/ladder/header.py`](diffhunk://#diff-383a9f0205ed40f71c07ed6f489056562f4ca7bc239c16b4688aaa547061e293R263-R305): Added several ROCm-specific includes and definitions to support ROCm operations and data types. [[1]](diffhunk://#diff-383a9f0205ed40f71c07ed6f489056562f4ca7bc239c16b4688aaa547061e293R263-R305) …
> [AMD] Ladder End2End Update for Matrix Code and HIP Codegen

- bitblas/gpu/matmul.py
- bitblas/gpu/matmul_analysis.py
- integration/BitNet/eval_correctness.py
Introduce efficient (but not the perfect) matmul schedule for int8 simt schedule for T4 Cards.
This pull request includes several changes to the `bitblas/gpu/matmul.py` file, introducing new scheduling rules and optimizations for GPU operators, as well as updates to the `bitblas/gpu/matmul_analysis.py` and `integration/BitNet/eval_correctness.py` files. The main changes involve the addition of a new scheduling method for dequantization, type and import adjustments, and version checks for compatibility.
* Added `sch_dequantize_in_register_with_config` method to handle dequantization scheduling without shared memory prefetch for devices lacking async copy. (`bitblas/gpu/matmul.py`)
* Updated imports to include `List` and `suppress`, and added `get_coalesced_veclen` from `..base.analysis`. …
> [Dev] Dequante SIMT Matmul Implementation.

- maint/scripts/installation.sh
fix llvm install bug
file in bitblas/maint/scripts/installation.sh
> [BugFix]Fix llvm install bug

- format.sh
- testing/python/tilelang/test_tilelang_flash_atten.py
[TL] test flashattention script
> [TL] test flashattention script

- bitblas/__init__.py
- bitblas/ops/general_flashatten/__init__.py
- bitblas/ops/general_flashatten/tilelang/__init__.py
- bitblas/ops/general_flashatten/tilelang/flashatten.py
- bitblas/ops/general_matmul/__init__.py
- bitblas/ops/operator.py
- testing/python/operators/test_general_flashatten_ops_backend_tl.py
- testing/python/operators/test_general_flashatten_tilelang_scheduler.py
- testing/python/operators/test_general_matmul_tilelang_kernel.py
- testing/python/operators/test_general_matmul_tilelang_scheduler.py
- testing/python/tilelang/test_tilelang_flash_atten.py
* add initial implementation of flashattention in ops/general_flashatten
* wrap implementation in config class and op class
* fix kernel name bug
* modify tilelang test script
* add ops flashattention test script
> [TL] initial implement flashattention op in TL

- .gitmodules
This pull request includes a small change to the `3rdparty/tvm` submodule. The commit reference for the submodule has been updated.
* [`3rdparty/tvm`](diffhunk://#diff-fa909c93fe94e9aa04c9e7f19e5754a2bb274678ad5c6275ee4bf54c6f9b1066L1-R1): Updated submodule commit reference from `f1ad5c1c57c15485d5da1362621f40749ddfa9a1` to `cd230c5cb374d7b6b7c51b3f34dbd4c0e598bf65`.
> [Dev][TL] Merge Hopper and Pipeline Modifications

- bitblas/gpu/intrin/lop3.py
- bitblas/ops/base_scheduler.py
- bitblas/ops/general_matmul/tilelang/dequantize/block_primitive_tensorcore.py
- testing/python/operators/test_general_matmul_tilelang_kernel.py
- testing/python/operators/test_general_matmul_tilelang_scheduler.py
- testing/python/tilelang/test_tilelang_dequantize_gemm.py
This pull request includes several changes aimed at cleaning up debug prints, updating submodule commits, and improving test coverage in the `bitblas` and `testing` modules.
* [`bitblas/ops/general_matmul/tilelang/dequantize/block_primitive_tensorcore.py`](diffhunk://#diff-a8892dadc6b24432ac9785d3a5def29c81b6e347d7b1b76b2cb7f037ce378022L404-L422): Removed multiple debug `print` statements from the `_normal_dequant_impl` function to reduce console clutter. [[1]](diffhunk://#diff-a8892dadc6b24432ac9785d3a5def29c81b6e347d7b1b76b2cb7f037ce378022L404-L422) [[2]](diffhunk://#diff-a8892dadc6b24432ac9785d3a5def29c81b6e347d7b1b76b2cb7f037ce378022L432) [[3]](diffhunk://#diff-a8892dadc6b24432ac9785d3a5def29c81b6e347d7b1b76b2cb7f037ce378022L442) …
> [Dev][TL] Implement Tile Language Dequant Matmul and Test Case

- testing/python/tilelang/test_tilelang_dyanmic_symbolic.py
* Tail split support for dynamic matmul
> [Issue 192] Tail split support for dynamic matmul

- bitblas/__init__.py
- bitblas/base/__init__.py
- bitblas/relax/__init__.py
- bitblas/relax/transform/__init__.py
- bitblas/relax/transform/apply_fast_tuning.py
- examples/.gitignore
- examples/relax_end2end.py
This pull request includes several changes to the `bitblas` library and its examples. The changes primarily involve reorganizing imports, renaming files, and adding new example scripts for end-to-end testing. Here are the most important changes:
* Removed `ApplyDefaultSchedule` and `ApplyFastTuning` from `bitblas/__init__.py` and `bitblas/base/__init__.py` [[1]](diffhunk://#diff-c2248c838997d60356d36c7ad50e42b7bfcc09238719cc55cccb6b87e48472e7L140-L141) [[2]](diffhunk://#diff-9c84240dd47215efaa914014a6dbe1cc47c8801fdfa8e98a51c8a907cb921610L15).
* Added `ApplyDefaultSchedule` and `ApplyFastTuning` to `bitblas/relax/__init__.py`.
* Renamed `bitblas/base/transform.py` to `bitblas/relax/transform/apply_fast_tuning.py` and updated imports accordingly.
* Added a new example script …
> [Dev][Relax] Update Bitblas end2end tuning example with relax

- benchmark/tilelang/benchmark_tilelang_matmul.py
Usage:
```cpp
#pragma unroll
for (int i_3 = 0; i_3 < 2; ++i_3) {
tl::cp_async_gs_conditional<16>(buf_dyn_shmem+((((i_3 * 4096) + ((((int)threadIdx.x) >> 2) * 64)) + (((((int)threadIdx.x) & 3) ^ (((((int)threadIdx.x) >> 2) / 2) & 3)) * 16)) + 8192), data+(((((((((int)blockIdx.y) * 16384) + (((k_iter + 1) / 12) * 8192)) + (i_3 * 8192)) + ((((int)threadIdx.x) >> 2) * 128)) + (((k_iter + 1) % 12) * 32)) + ((((int)threadIdx.x) & 3) * 8)) - 8320), ((((1 <= ((((((int)blockIdx.y) & 31) * 2) + ((k_iter + 1) / 12)) + i_3)) && (1 <= ((((int)threadIdx.x) >> 2) + (((k_iter + 1) % 12) >> 2)))) && (((((((int)blockIdx.y) & 31) * 2) + ((k_iter + 1) / 12)) + i_3) < 65)) && (((((int)threadIdx.x) >> 2) + (((k_iter + 1) % 12) >> 2)) < 65)));
}
```
> [Dev][AMD] Implement conditional async load for AMD HIP Backend

- .github/workflows/benchmark.yml
- README.md
- docker/Dockerfile.cu120
- docker/README.md
To ease the process of installing all the dependencies, baseline software, and Ladder code, we provide a Dockerfile and a simple guideline to build a Docker image with all of above installed. The Docker image is built on top of Ubuntu 20.04, and it contains all the dependencies required to run the experiments. We only provide the Dockerfile for NVIDIA GPU, and the Dockerfile for AMD GPU will be provided upon request.
```bash
git clone --recursive https://github.com/microsoft/BitBLAS BitBLAS
cd BitBLAS/docker
docker build -t bitblas_cuda -f Dockerfile.cu120 .
nvidia-docker run -it --cap-add=SYS_ADMIN --network=host --gpus all --cap-add=SYS_PTRACE --shm-size=4G --security-opt seccomp=unconfined --security-opt apparmor=unconfined --name bitblas_test bitblas_cuda bash
```
> [Docker] Add Dockerfile to set up the application environment

- bitblas/relax/transform/apply_fast_tuning.py
fix for issue #259 , as build pipeline is not working for private prim function.
> [Relax] Fix end2end tuning for relax graph

- benchmark/operators/benchmark_bitblas_matmul.py
- bitblas/base/arch/__init__.py
- bitblas/base/arch/cdna.py
- bitblas/base/arch/cpu.py
- bitblas/base/arch/cuda.py
- bitblas/base/base_scheduler.py
- bitblas/base/roller/policy/tensorcore.py
- bitblas/base/utils.py
- bitblas/gpu/__init__.py
- bitblas/gpu/matmul_analysis.py
- bitblas/ops/general_matmul/tilelang/dense/gemv_simt.py
- bitblas/ops/general_matmul/tilelang/dense/matmul.py
- bitblas/ops/general_matmul/tilelang/dense/matmul_simt.py
- bitblas/ops/general_matmul/tilelang/dense/matmul_tensorcore.py
- bitblas/ops/general_matmul/tilelang/dense/matmul_wmma.py
- bitblas/ops/general_matmul/tilelang/dequantize/base.py
- bitblas/ops/general_matmul/tilelang/dequantize/gemv_dequantize_simt.py
- bitblas/ops/general_matmul/tilelang/dequantize/matmul_dequantize.py
- bitblas/ops/general_matmul/tilelang/dequantize/matmul_dequantize_simt.py
- bitblas/ops/general_matmul/tilelang/dequantize/matmul_dequantize_tensorcore.py
- bitblas/ops/general_matmul/tilelang/dequantize/matmul_dequantize_tensorcore_finegrained.py
- bitblas/ops/general_matmul/tilelang/dequantize/matmul_dequantize_tensorcore_weight_transform.py
- bitblas/ops/operator.py
- bitblas/relax/transform/apply_fast_tuning.py
- bitblas/tl/base_hint.py
- bitblas/tl/mma_layout.py
- bitblas/tl/mma_macro_generator.py
- bitblas/tl/tuner.py
- testing/python/operators/test_general_matmul_tile_schedule.py
- testing/python/tilelang/test_tilelang_mma_macro_gemm.py
This pull request mainly shift tvm intrin related import into lazy import format to save the module import time when we write `import bitblas` in python.
Before this modification be applied:
```bash
import time:  39164.91985321045 ms
config time:  6095.165014266968 ms
hardware_aware_finetune time:  33147.03679084778 ms
```
After this modification be applied:
```bash
import time:  2109.856128692627 ms
config time:  22495.219230651855 ms
hardware_aware_finetune time:  49844.87271308899 ms
```
Test script to reproduce the results:
```python
import time
import_start_time = time.time()
import bitblas
import_end_time = time.time()
print("bitblas.path: ", bitblas.__path__)
from bitblas import tvm as tvm
M = N = K = 256
A_dtype = "float16"
W_dtype = "float16"
accum_dtype = "float16"
out_dtype = …
```
> [Dev] Refactor codebase to save import time

- bitblas/__init__.py
- bitblas/gpu/intrin/lop3.py
- bitblas/ops/lop3_permutate/lop3_permutate_impl.py
- bitblas/version.py
- setup.py
This pull request includes significant updates to the GPU intrinsic functions for decoding and interleaving weights in the `bitblas` library. The changes mainly focus on enhancing the decoding process with additional features and fixing a bug in the interleaving function.
Enhancements to decoding functions:
* [`bitblas/gpu/intrin/lop3.py`](diffhunk://#diff-15fd74b90c3b956e9864e35778f26b27f6c9a7cfae35037967f420fda9a0bbe5L688-R752): Introduced a new template function `decode_i1b_to_f16` with additional parameters for signed integers, scaling, and zero handling. This function supports different modes for zero handling (original, rescale, quantized) and includes the necessary logic for these modes.
Bug fix in interleaving function:
* …
> [Bugfix] Fix correctness issue for float16xuint1 with fast dequantize

- setup.py
This pull request removes the composable_kernel include from setup.py, as it was causing a compilation failure due to missing submodule support. This resolves the issue mentioned in #278.
> Fix: Remove composable_kernel include from setup.py

- bitblas/ops/general_matmul/tilelang/dense/__init__.py
- bitblas/ops/general_matmul/tilelang/dense/matmul.py
- bitblas/ops/general_matmul/tilelang/dense/matmul_mma.py
- bitblas/ops/general_matmul/tilelang/dense/matmul_tile.py
- bitblas/ops/general_matmul/tilelang/dense/matmul_wmma.py
- bitblas/ops/general_matmul/tilelang/dequantize/__init__.py
- bitblas/ops/general_matmul/tilelang/dequantize/matmul_dequantize.py
- bitblas/ops/general_matmul/tilelang/dequantize/matmul_dequantize_mma.py
- bitblas/ops/general_matmul/tilelang/dequantize/matmul_dequantize_mma_weight_transform.py
- bitblas/ops/general_matmul/tilelang/dequantize/matmul_dequantize_tile.py
- testing/python/operators/test_general_matmul_fp8.py
- testing/python/operators/test_general_matmul_tilelang_impl.py
- testing/python/operators/test_general_matmul_tilelang_kernel.py
- testing/python/operators/test_general_matmul_tilelang_scheduler.py
This pull request includes significant changes to the matrix multiplication and dequantization scheduling code in the `bitblas` library. The primary changes involve replacing the existing TensorCore-based schedulers with new Tile Library and MMA-based schedulers. Additionally, several files have been renamed to reflect these changes.
* Replaced `MatmulBlockScheduler`, `MatmulFineGrainScheduler`, and `MatmulWeightPropagationScheduler` with `MatmulTileLibraryScheduler`, `MatmulMMAScheduler`, and `MatmulMMAWeightPropagationScheduler` respectively in `bitblas/ops/general_matmul/tilelang/dense/__init__.py`.
* Updated `MatmulDequantizeBlockScheduler`, `MatmulDequantizeFineGrainedScheduler`, and `MatmulDequantizeWeightPropagationScheduler` to `MatmulDequantizeTileLibraryScheduler`, …
> [Dev] Rename signature `FineGrain` in Kernel with `MMA` as `MFMA` implementation will be introduced for rocm
